// swift-tools-version: 6.0

// This file was automatically generated by PackageGenerator and untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

let package = Package(
    name: "JustLog",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v13),
        .macOS(.v12),
        .watchOS(.v7),
        .tvOS(.v15)
    ],
    products: [
        .library(
            name: "JustLog",
            targets: ["JustLog"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/SwiftyBeaver/SwiftyBeaver",
            exact: "1.9.6"
        ),
    ],
    targets: [
        .target(
            name: "JustLog",
            dependencies: [
                .product(name: "SwiftyBeaver", package: "SwiftyBeaver"),
            ],
            path: "Sources",
            swiftSettings: [
                .swiftLanguageVersion(.v5)
            ]
        ),
        .testTarget(
            name: "JustLogTests",
            dependencies: [
                .byName(name: "JustLog"),
            ],
            path: "Tests"
        ),
    ]
)
